yarnPath: .yarn/releases/yarn-3.6.0.cjs
nodeLinker: node-modules
# nodeLinker: pnp
# pnpMode: loose
# packageExtensions:
#   debug@*:
#     dependencies:
#       supports-color: "*"
#   node-fetch@*:
#     dependencies:
#       encoding: "*"
#   vite@*:
#     dependencies:
#       supports-color: "*"
#   "@types/react@*":
#     dependencies:
#       scheduler: "*"
#   react-redux@*:
#     dependencies:
#       redux: "*"